### ISSUE TITLE
Unable to load the map resources

### ISSUE THREAD

**Issue by wilsonsilva** [pierreozoux/housescrap#5]
The live demo is broken because the map images aren't being loaded. It seems that your Leaflet or OpenStreetMap api key has expired:

![alt text](http://s30.postimg.org/3l5ur6jld/housescrap403.png)

**Comment by pierreozoux** [comment]
Yes, Thanks, I didn't update since my tile provider closed the service... It's on the todo list ;) Are you interested by this application?

**Comment by wilsonsilva** [comment]
I was just browsing. We both replied to David's issue and I clicked on your username, then I had a look at this project because it has a funny name.
